# какие сервисы будут запускаться
services:
  # придумываем имя сервису
  web-app:
    build:
      # указываем где искать Dockerfile (нашего приложения джанго)
      context: .
    # прописвыаем какие порты должны быть проброшенны из данного докер контейнера в нашу систему
    ports:
      - "8000:8000"
    # подключаем локальную папку ./service к папке в докер контейнере
    # те все изменения в локальной папке будут происходить в докер контейнере
    volumes:
      - ./service:/service

    # указываем какую команду нужно запустить для запуска джанго сервера
    # sh -c - запускаем линукс shell, 0.0.0.0:8000 все адреса на данной машине на 8000 порт
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
